<!--
document.write('<object id="player" height="260" width="240" classid="CLSID:6BF52A52-394A-11d3-B153-00C04F79FAA6">')
document.write('<param NAME="AutoStart" VALUE="-1">')
document.write('<param NAME="Balance" VALUE="0">')
document.write('<param name="enabled" value="-1">')
document.write('<param NAME="EnableContextMenu" VALUE="-1">')
document.write('<param NAME="url" value="/ads/pic/1.WMV">')
document.write('<param NAME="PlayCount" VALUE="1">')
document.write('<param name="rate" value="1">')
document.write('<param name="currentPosition" value="0">')
document.write('<param name="currentMarker" value="0">')
document.write('<param name="defaultFrame" value="">')
document.write('<param name="invokeURLs" value="0">')
document.write('<param name="baseURL" value="">')
document.write('<param name="stretchToFit" value="0">')
document.write('<param name="volume" value="50">')
document.write('<param name="mute" value="0">')
document.write('<param name="uiMode" value="Full">')
document.write('<param name="windowlessVideo" value="0">')
document.write('<param name="fullScreen" value="0">')
document.write('<param name="enableErrorDialogs" value="-1">')
document.write('<param name="SAMIStyle" value>')
document.write('<param name="SAMILang" value>')
document.write('<param name="SAMIFilename" value>')
document.write('</object>')

//-->